package com.example.Employee.Management.entity;

import jakarta.persistence.*;
import java.util.Date;

/**
 * Represents an Employee in the organization.
 * This class is mapped to the 'employees' table in the database.
 * Each employee is associated with one department.
 */
@Entity  // Specifies that this is an entity class mapped to the 'employees' table in the database
public class Employee {

    /**
     * Unique identifier for the employee.
     * This field is auto-generated by the database.
     */
    @Id  // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Specifies how the ID is generated (auto-incremented by the database)
    private Long id;

    /**
     * Name of the employee.
     */
    private String name;

    /**
     * Email address of the employee.
     */
    private String email;

    /**
     * The date when the employee joined the organization.
     */
    private Date joiningDate;

    /**
     * The department to which the employee belongs.
     * This creates a many-to-one relationship between Employee and Department.
     */
    @ManyToOne(fetch = FetchType.EAGER)  // Defines a many-to-one relationship with the Department entity
    @JoinColumn(name = "department_id")  // Specifies the foreign key column in the 'employees' table that references the 'departments' table
    private Department department;

    /**
     * Gets the ID of the employee.
     *
     * @return the ID of the employee
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the ID of the employee.
     *
     * @param id the ID to set for the employee
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the employee.
     *
     * @return the name of the employee
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the employee.
     *
     * @param name the name to set for the employee
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the email address of the employee.
     *
     * @return the email address of the employee
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the employee.
     *
     * @param email the email to set for the employee
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the joining date of the employee.
     *
     * @return the joining date of the employee
     */
    public Date getJoiningDate() {
        return joiningDate;
    }

    /**
     * Sets the joining date of the employee.
     *
     * @param joiningDate the joining date to set for the employee
     */
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    /**
     * Gets the department to which the employee belongs.
     *
     * @return the department of the employee
     */
    public Department getDepartment() {
        return department;
    }

    /**
     * Sets the department for the employee.
     *
     * @param department the department to set for the employee
     */
    public void setDepartment(Department department) {
        this.department = department;
    }
}
